name: Notify Discord on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send release notification to Discord
        uses: ilshidur/discord-webhook@v1
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Test"
