name: Release to Discord
on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Discord Webhook
        uses: tsickert/discord-webhook@v1.0.1
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Update"
